version: '3.8'
services: 
  bookmark-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmark-api 
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - dev-db
    env_file:
      - .env
    networks:
      - freecodecamp
  dev-db:
    image: postgres:13
    container_name: postgresprisma
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: